/**
 * 画面に埋め込む素材
 *
 * アプリ起動時のエンジン音。利用者が撮影した動画の音声から、
 * セルの回転〜始動〜アイドリングの部分だけを切り出したもの
 * （mp3・モノラル・約4.3秒）。
 *
 * 外部から読み込むと表示が遅くなるうえ、Apps Script のサンドボックスでは
 * 読めない場合があるため、データURIとしてそのまま持っている。
 *
 * ブラウザは「画面を開いただけ」では音を鳴らせない決まりになっているので、
 * 起動画面のスタートボタンを押したときに再生する。
 */
var ENGINE_SOUND_MIME = 'audio/mpeg';
var ENGINE_SOUND_BASE64 =
  'SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjYwLjE2LjEwMAAAAAAAAAAAAAAA//s4wAAAAAAAAAAAAAAAAAAAAAAASW5mbwAAAA8A' +
  'AAB4AABmGAAGCAoMEBMVFxkdHyEjJiosLjAyNzk7PT9DRUdKTFBSVFZYXV9hY2Vpa25wcnZ4enx+g4WHiYuPkZSWmJyeoKKlqaut' +
  'r7G1uLq8vsLExsjLz9HT1dfc3uDi5Ojq7O/x9ff5+/0AAAAATGF2YzYwLjMxAAAAAAAAAAAAAAAAJAUxAAAAAAAAZhjq0q0VAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//s4xAAABngzQ0SEZEFqL2hdhJT5AEDIBBJWCL0B0ExOSfd3c0Lv' +
  'wIIOYfxBUcP4Pmv4f/+INY8/lHAh/+T/lw/QGPz6NRwDvASVUUpgQjQTLgd13VTTEbFTkJlNcBCRGysQNJIkS+dv9PE17ZqU61AZ' +
  'iCn7NuiIk7GagdFP///j/uOqjs+ZFd1lmm1N0chHkvVr3av///931eqxJFEmcU+jcNUAIyDQQLAQ17iJYyWAXlldJHeOAbh8RBJR' +
  'vicBw/mpbAoUOyk1i2duJD9ufhVfWGb52udA//s4xBoADL1bPMwwScnEryhphZXgOd4ceMICnQJUEv///ucO5ATKVyM52rY6UniX' +
  'VSoq1Vzn9yGIyMy////uEEgJzk5fjWIAwBBkkt0PwV9MQVChbD9qKs0RHjdV+3Rd6UwmkfexYOdxcQRZVZlpn69G8qhVrbuzriXD' +
  'GYg+26jxSOOOYTZ9///0kCwoOiIxxcEMpKIRVPRkS4kxHVUFA8NF2Iqo5ULdqnM////uzur7tPMLCzpn6CgQE8G7KXk1hA+8xZ1k' +
  '/Yonjfbg+DmuSaIhQdBwGoRw//s4xBACDO2BQGwkrUGZsKg1hgj5KU59S+NHWlKlijqxFqnW+wKgj7yCJhIpmUI2fT//9yKcVFyn' +
  'VTG5CrzvVGU7FZBzotGXKWYyK0iP////qrVNglTEioq46VMIEVtEFPhNBG4OoyYcAqKgcs4MWh61BaTurDzmfhrAuOkqhMVUO3jS' +
  'aZi77hB6CYN8yO30YKZ8hnZ6F///KjXM6GlKxpnFKFRKGMyHVhZ0pObpZbGYnRf///7NVDSuZhJVCIJHHR4lCMJYoAIKtRE4YDVV' +
  'N9w46pSv2FCk//s4xAqATF17NyykqMGOrua1lJSxawhCrRlEVJWSoBPjGKZzh2ApflWJYk9RWn7GW2apSzCqv//0h0hmaimEKGQz' +
  'MMM51dVKhCzGZpTsTMUp3WQ5HlI////03aswyJ5xrojQAQIgHYciOqHaiWlLmFyHlMuRNqiV2iof9T0oC5OhH0kAtqzCQmT9Q+L/' +
  'kOguzkcjN+SQSipHH//+bZkRJ0dXac1hMWHoU5RcM6MPIIs5yRp1FymZy2uT////Zy3sZmGYKYs7JQECRXYji7tkyhwjglmiirD7' +
  '//s4xAiADPl9P+wkTYmGMKq09ImndScWfI94NfzekDALmhl6yYZTbkXJPiO8+ru//UiUEhPHegT29UuL7mK7FbE0PDjkCMT//6Vb' +
  'nrp+7IZ3YzvzXyLYjM1mV5UlL////50OKIIOjTAhNRhUF222ORtMgsXVR4KcKpXnkxmUh8bJelepBKBAUVE70cuvKA4uj+8jI5L+' +
  '0ZOZQcDHSiWRmUOLQgJScq2X8jf6uchQ7p6rq+elj7SOj7O8ib3t9V83///8nTiggtsKhwhwsBUlS3TbW2xAMTfu//s4xAUADBCX' +
  'abTHgDGLMq43DNAAfqvhPo35JgmrFddU5OEkbQ2ClekKLarV2fzw6C/xI6GKyksiGVQ+Q7Hakhqd9NLGiR9sN7WzdtTu8R22BHqq' +
  'UNS7mEkAgI1LHkHnKR/FE9f////9PKGkQmY1IogwARCAgEAIALjLhDftaCfPYYAUzpsTCg9Z8wLpmSAQKbZumnD0oyQ/T603QZzE' +
  'mdl9NTINy4YHRykNnX/+r3Qm9dEkymkX2//t/+brcwNE2+//////vUikmm5qOeeVY3WEIUMBAAE2//s4xASAC9hnef2HgAGDrm20' +
  'kYpRKsscJgqlwk1v3hcB9rU7Ut/vHmzeYz1OJQm6ZA8tvdahQoLLC1XH0rWSeZvsro7Lvh1+kNA1NBr/6jVx3OgYqGloSlIsFUHg' +
  'VFlAWRLAr+Coi26bjqYAAwQAAkATAWaXIx4jEghRxaWK4muT+LK4IptIWwMhwoONRIApDtWCjDKF+o4r0gAWRocQw6NhnLVP/17m' +
  '6uN5tVskzszKxnOCMJdGYQdzFq1tWZF////T6MjiB8F2VUyqiIsRQRgSSmFkgcgz//s4xAYADD1ZbaYMtEl/r2zowxaJfH8tmK4R' +
  'JXrFUD+RLyIOa0MZ01TOa9aNakajYoNaJZi8IRfWY1WhaopW/Uv//qymbFVZFR3KUiVRzFsVVmZ0MMYXQpUr5XtLIi///FBQ1xR9' +
  'uhUo/jSARABGMl0VFVwqJZbLBIOpUJVcaRX81eI2FuYmg7LCzav2zjuKdFlNtSXz1wbVDOTOyBkRaH+opGp//1MPNzozJmLV0OdV' +
  'rRJJ0RjMz1qi25X0fH//+qUfa/OzyD0Wjo6HgJRAdGTtljn0uzpP//s4xAaAC72DYueYUomIr6yM9IpJRWvKsZdE9Gwq2CSVWRCS' +
  'nWehHBoEYf8K1FOTnMMqOi8XKf4QyoCuzTe3iZS//+0pb1qxWI5T1K6IrXfKVz0q62R6J9vX////6GFAjBUQsNN0AHQVRtTt51qt' +
  'zSymNDcsASRAN66OiI4TwTmMA4CgCGCzhBPDZZy4baadkm63KKCMvM4o8noYcKN+ov//6i4dyOQSrpfpsp1YhGOEEAbgzpaZ0Iq5' +
  'zIgusn/////wQ1UH3xSCEgMRAADdaVwEsEnxeIYE//s4xAgBDFV5beYMssF+MC509Im7hYKzlchnAqEhYuL7DT3oR+ywP4Co8ocD' +
  'HDCQwD0YMK7SYE36wR4qEzB83EA43UEP//97MyMh1r2Kl0Ramdiu5Xl0UqESahe+Pb////1J6CwlIVwAJEqRJ8JkOqAoFmRvhl83' +
  'lVq4xXxc1PVqWQm6WI9jJVmhUfErK2SQ3/0o0/+G3C869eNCJY8hRFAN5//Ed3//oZFa3lL56OjlO2Ul6tffttRD+X////qv6sok' +
  'MQUjxVUAkACikk8Kq1SFaWEyUZKW//s4xAgAC3kBaUewSdFQIW0k8wl+/DKgvjB9CdgciRsEojNnJZT2hZzPEolLex4tNqZveBJv' +
  '4h7qRXClQ8UcMVH+gF///AqF9k0UMbMwkMaKcxpyjFZ7dWa//4keSd86W1LAEX0wTwsRzArxzKs65zg3aQLMWck2HL/0sQHAHrOd' +
  'QLUa3NE5e37O3sbqiypUd/ocIKQMn8t///l+pGZb3MDGgMwpXYoeirwQWhzTy4Sd/+sBLYAAE8pAR+Hy65jIoMk61qJwb+3oRnop' +
  '559x8UoXLNFsGxE6//s4xBGBCj0LVuwkrRlVH6lJl5VyLutBzGpLdJamY5m1dEiphUVR1cpRVT//r//t9U+11luh2FlgMLGfqoq/' +
  'LJbhc3oDCBBrKRRkD41BZBMeWPRI3USOA13jS/VtxAGdUVhnQXZiD6JS9/zJHdN7XSOxwFNfT3d7V/UrR7IORDTqE2DgiP6N///o' +
  'T6qZbuR6d7vqxREoWovKKgS07wF2GwzjlL8BNQ1gyTNBoiXaFYy0KzAbkqoNDpOiW/8JrGv6hpTIYYKoL6lKbUkDRpgw/QT///od' +
  'HqhB//s4xB8ACmj7TmekR8FKjmn08wnIGrqySo2pWvOKICyAkLhVeXej/+bmQABEACCjJvgpSUk8H8a55mRgmCXT5bzqbPI3rBQv' +
  'Joqx/lfDKIAPGly1Bl1JIGCwXAoOOk5H/g2AhgfQDCg4MBoVYsBPlxiQMQKNqZb//MHdrCUgExpJ392FWrDmxQEbeC0oUqCvK1gh' +
  'avvYXBUhuFnTO+YWJ5z8Hsef3eYfu3BaaszW1c1AW5Tf//+pFKdw4IHRKWWbUHjTuHA6L1s//8UUGEtLgBgCG81FQf5d//s4xC2A' +
  'CkTLX4ekTbFXEGko8yGY0NMkWYdwjKpeKptbjvZc9BhgQQq5Y7rGPkWa5U7UgP8HSzXq0xEOxFvdmdQVd/yTxqFyaKUp3iEBgM8s' +
  '6F5rNO//y4EKBgoIygEDDxokG8cleT0EVYw2Lq4F4ORhfboYKjg4lHHISMykDhI5ymVCtXRskujg///////sljPamrIZk9imP6ao' +
  'Xd5S1KWaVv/+rIpilMsCFAJgomU4wYGKKkvYBEEdE2wSCXYypJtdrAD4fJAZJ2QCkTCREaLCia7bqRPY//s4xDsACqF9RkwwQ0lc' +
  'EyhdhIyw9WEsY7Nw9e9jB9etYH1juCFAmQMyxQEBIGwEDLoiiWCp3x7rZAjtW8tDDVokVf/5IsGzdIqYSAgcl2W1DhL0T2fSKM7V' +
  '8bRunI+Z2wbEytKI9SEENzl+wOeGCY7UDGiU/gRIn0WIuJPkhrYi6B90pW3//+6K/8z91YrIPHi8RvE4ga9BEdF93/s/WFyngDCC' +
  '8DvSLIJGLSpC4NxuQ2VbjHW9Q1BQFyyD7/iBw+k6LKoijPUoMqMo3zOC/l/dit2BBrSq//s4xEaCCpTpNCw8qYFVEecY9IoYJB//' +
  'rNuKteuplpIOgQcbGHREDK2vcOHIX/+omlcRTAAlCEAC6ixuCsRiJZFKf80Y/kJWu8eK5AYbWEx9/CMJFEf20QlmthIiGYktqvf5' +
  'TiviYsgRoZUOhL//+pCoWv6aOz+hCviguNuOZtOj0OrEHONYHVAKg2JjIGQFv3WSpYYBS+CKDRBwrDUG6Um2OitqwaOQkPPg6FqP' +
  'G7NQh0cOL1H/iLewdQK+osOUZ//6zOYiEZTHV0Ya8Pl/aVOUi3rP//q5//s4xFMACpkpPUeYsqFKG2ZJhhT5zFUAGAQo2SQAowKn' +
  'WMX6Z6+hIQhsHzbVitai4JvQxDRaDKNQhixsXMiPMWguEY791bDsQh3//Ajnd1NtVlK68v8V/+lzBhen57foDvst44OH6pHv3f/v' +
  't/6CkClTbjbIQCPGUtTPUkmbSsNnZ7I5gKjYvVLpkmd7IrRoWYZ1CNRt3ogP41o1xjf7+qRTK9FTt+4kR6O7EX7kO6kfR62M45Eh' +
  'xy0rW5+KgkJf/hKgmhAHBagoEwR/rQYEkcqXMovBjW39//s4xGCACui9N0wlBclVnyh09JWkboy5pzBSjxhKWjQ1IyukBYgEopIL' +
  '6UAiiIs/Dwe/hQMAwL//qAQv5GX//60e95lEkMLW55TD4kdnUWLlF/u//GTY4AjdDAAAyYOTGJSoG80yzzGVMZeaMtQTVP2WKLrl' +
  'TfQpth0Wg1HBooLF+Vv2HhwGM7f/Gl3IggNeHxeKG///asqKq3oQpFs6M98TBgEqYWYqAQBYAOuTZSgWakInnF3ud5pLR34jbut5' +
  'DdvKBY2/8/ILcStyl+ZTz//5kcpkV4VQ//s4xGuACtEBNywwrMFBIKYdhJWYYx2L//+jbTIRrohDjkPVBj4IVeykFKZaMDv/6HuR' +
  'eTKHsYF6PnjCDjIDVipboePpkgHBRCThZ0xhjE6fsmTgaf216k4srn/8Sz0Glf8TkwWFtDI3PejIzU//+i7/ck10LFSJdmMe8ipr' +
  'uXZbljbtVp5FoCFf/+KKDrqNFQICtkAEBRKcyOBCb/wCyCH0lIxHGGMpUCVVeeDoMgR8XmgXEjJLTc7YsMP9QVU1CzCoFKn+pEKg' +
  'X22WLozjKkmXx6HCeiXH//s4xHmCSg0TLMwAVIFsIyTJp5y4T//+8uHt8tJoxEhF7QyQ31OZ6fZCp8Bk5NA3/95BYvhV9TQKsAAD' +
  'FYFEL4J5YYr5LxIotaZorakyp5V164pOinbcTs29wBevTkof6HfzzOUAuNi4indDPQIQ7q4pGo4RLiA+e4pIv//+g2Kn9Kpl5taN' +
  'CDeJUU8swrSrGdw4xtxa5//8iPJpEmgAcdJAABLcToQOva80hYVgMJcP6ZmK+lNQMWpulYw+B4hIHQllDK5awUGypPpGKw3GmLmT' +
  'e//+DhOg//s4xIUCDTkZKu00cYGZImVlg46giuwWDQlY/OxOyazBtRP8Ln//0w5kyI6KTvnEpaQwrm4+8wg15bCJRlsmz/9DQI0y' +
  'OAkcBTlsaJIFaKzcTLPg6+ECQVIsy9+2EkTrHO5OKnYlAxq9DzlIWdioVjgQQA0M0nGT2EY2wTzC002Q0FVSG+nsZk+WFqvooOgP' +
  'GS3tF8zX+Xr7nHTMy3OxQgBm9KFdXPYxD+r18+x0CymS5e8nZm+SxLeX7f6bV/rsRR7v5P31t+ZbYbD5P61g+QchvwJGlshC//s4' +
  'xH6ADVj5LOykcsIwJqm1h7D+gRCYe6CTUb1DUzFPizElNQyy6JyOdBXiShBzXmNyhxJ0/mFwjrp+pk1Aw55fqpS3p/4UmdGlHYlS' +
  'f0ZWGQ/eIlTE7NAJGqULU8JTR+1Qa+Fp5//L+XXJ4ogqWXaEIWROLoG0i1GUgQyQbKW0RisRiIV4FHRkTt+DpS3KrIeEq/GVkDl0' +
  '5I0D//qBUCNpj6dhmLkQmMIABYRAGoM2G4ggDwZ9voStXEV88jumE0xDx8AqGIesu460fDrJEcJ7uD+/99HO//s4xGSBEwk7OEy9' +
  'LcmhJiho8Q8QLY0VxT/3qosgRjhlDJysTt//+5iILNIRGp2AgofrSPyAsGFIE65vkX8uhE+amMQzrCn/lFoXYMWNqIgBNqEt8BRI' +
  'LRoEEYYtAstzNPaX71BQarqqg8KzSFdYi2vVWUbaf9seNJIHm/mlKE3UaKCI4WGGddBf//8zubNdV+w47OSlamOxkD3zdJ0pWbVf' +
  'n///3SSiRg51UAiO0PdyyaaSUAkA9RltCYdPYyqjYjZgN0KPQ5okaHodMKIZBEVElMLB5COq//s4xEWADDV3T6ykp8lum2rqnlAC' +
  'AMUMISe7ULRDEYo0bMRUVRhj//+1XJSiStQYNCaNLyhgBk/MABOs7u/+eLwaEVYKnQZVNjmpzE20qDmD2Os8Vo3gAVdyXKRCHrNp' +
  'AN54l1Y3ZPRM2aOciOMR4r3JR7bU+4M0SBLWa0R62Jwo4T554mfHx2+JtaamWaPjWX7z3vf779fdyz/+Z7N6//ztk0TeP9Y0q3Bt' +
  'hUUDA4f/Gb5nifMjg8/3/f/tBZHLBkZGyHaK+q8/gRsbvT////GqU/pr//+b//s4xEgAFAlzbfj3gAGLsGv3mFAA4sp3JWHA0u3F' +
  'UBiismDhawEbwQIAAAA0JiyvOi3AD4fgxMLpcSUKhijURcOgwDBwXO7iMhjC4dQjuIAgqZ5WFB5dL1LFXM2IsUaKqZ///6/6uKSh' +
  '4qkKUt/6CQmUOqrKW6lZqzNL////7NWSUpRSYhsWdSooG5kAEAABcDYR0WmWH5jqJAQqmiEsSZBXRgr1SMPNROiL5AQlDkN8gjlI' +
  '4/kUaCDUKQ/IxCD6Z3T//9HqQ1EZGZyRgqg4qC7ntTFBU7po//s4xCeATL1xX6SctgnRr+wswqbxRt16j2crTwOJi7///7p6ugoD' +
  'l+BUrxRIVhZAEyNtbeZRYpqwmiZaYYUrwfaiPOWrV8bxXHIOy2b2SrK52hIhZhr1REKKCqGlIVxwshUkPR1///Zj1ZGIRHVSkeFC' +
  'iIo8OCLGcUGOH1DWIqCLbEMYqOVHHHHgIHRcPkX//yMryEyuWDZV7KOZtc8h5KqNhneEEgjkqVYKg/zvO7Ti41bXtHN6/tazVKUD' +
  'YNSXXWyKKELljz2Niu1ve5JVZqdulWVnFghX//s4xBuAC7kxceegTYF8Lm39gwmg//51oYzt9a0zUVDlc6nO9HClGOtm0ZldjJG4' +
  'Q6ihA/+WcRBsXEBufareIEATThLwSmInLrSd43BTGAZS7OfUJMPusmgLs/eBVhNcF33yCaXy5Z1EZBcLU5wN0I2RkasO5Ho3/+Uo' +
  'HI1f/ShTj2uSR0oQtn5/VUWVWSj////0LQ11I45Dmr6NlZhlMQaSiMwSCFIovLZRpwwK2sieDqqbnKxbtuokM7lZkGhD4z5rZEci' +
  'tYvV1MpjbHZNf//qxnrO+3dD//s4xB6ACojjceeYTQFrq2289JT9IoVCTBXBp6e4q422j/5gY+swInrD0SpW1N4RkBEVoA4JMGAT' +
  'eRtliqW+OBymvsdr+XpEi+Oe22kZld5i9ke7rdmR0CDixmK0TB1GCyO3//5f+WiUP7yqd2MZ9JURno11MR5etZ///iqoLzUfeO/H' +
  'R+XN1bbdrXHX4MFQ9CcVKGUV3bOvHDlS2L34aihjk6aMtsie3zGzXxn3ZXpRwTno8t9u2w+n25vtDuRW9GdWOjHT/00/1r81Gqmy' +
  'W/ds3///Ul/q//s4xCgACrVze4YYTfG2r+z0kRuZYQL1ihlbam1hZSDQBokhVWab1ZkxPSIkmpO/hARtoYW4gYVTbWJE5zC4iBht' +
  'An2egxT7P1//FZGpcMKEiYqPS+1a7e/+1jkKh1oOUWV3sL9kI+ivMRpmI3RtnOczEV9Xkor//kU6EaeRqmGpKJxnT+Gi5BW7bfZx' +
  '36gh3Cki7yciAw8SAImGBKAy4ebl0P2hYfbBKI/YL02p56RjlF5zpXyjkfTpa+kVhFRvkf//9/2mzMTK61JnJ0t7nTq4I2t/v/V0' +
  '//s4xCeACk0bhYSYT3FYo+388xT4QEmx0bCEpqJACGwVBUHSDUOFdpbcdC1biGMOmh2xjzUPrLX61cIHfuPSR+TRkUZsqqJjRUcD' +
  'B30EH//9Er/62s3ap5jstyq7u3R6pFWGjjd/+iIXDzonKnalnIZkdyQEyoS+AuCa6Zzomqa80zbEr80DmmpT9V7lpuiA1IJdzg3q' +
  'rM7kmYvQGwdU+Upv///50Kn/Mnfs12bOy+t/dKM/5v///zbMTQVQdSs6wSIf3RmJDMESiCaBk1MDYDukYyM3ZdrC//s4xDSACmmH' +
  'deyYRYFamu39swj48kvTnnD8yTE7NMn1yycOya1HAsfqspWqdWRWcxwR79EDn////mX+yFEGBK1+Jw0WCS0Jyb0nn//wnVGB83Bp' +
  'RxROO1NJFEolQBsgNIlLzuqWMHDdC7Lr1HQgwcg2z780PRkWnqIqNLlU+kxVZd0EUBTD1IjoZf//+5Gpf+kVd9DkWneXXYd/7Im2' +
  '3////l0lMwkS0rUHa2211j+4GIKtLRPxFuWCyoa2REsDcDYeLsh/CprbWNB6O/KV8FWWjGC80GPT//s4xEEACq13daewpdlYnLBw' +
  '9Ij+sgIDdqFKZyh2vCgv/6GFcpv+T1HxaoaFc+B3UA1U56v/nhUa8BhN7WGqEXtShBAJAVEgNXqFqp4sK0yOaMWj6pKI7qUlBN0G' +
  'BIjAiMgb7kzUeDRTmRgGbSoQA+rf/055V6S8/IHAn7rNWx+6Tte1t1pvo///+stF1F+CxCRdFsJyZ+ItBgKYHEIvFs3TbXepUGEm' +
  '8o+2gDHjaCRaEcDj9DyaKeI2Lp+ZJSJYEnOMch+d///yy/6lflEcjpdXJOx+ZSpI//s4xEyACqlvZ6YMUElarq10kYogzMOytOdP' +
  '///u1HeQuk4sTkovG2q3ZIBgBYHshQz9QY/iVeTxsedVQ5dX1NqNa7yyoiPITgrPCWXtNiOXsi0MVd06nUzM/I///7zdfUzHepX7' +
  '0jTvKTq5utcvp///+vRamsGx2cOC8lCaRLqrwSHQWyXwdw/hnKViOZX5nDwklTBND1RAJFkEHrSqpoxxVaa0ntZEYs3ZAoVS7TdF' +
  'iMU////I3dDNuiYwBwwggsgtMP0H/Zs/9gWWo+IDKzxoGDhZNndW//s4xFgACrV9aUeMtJFZHC489JT4QyhSQMw0cAjfn11zamsx' +
  'KSUj6UKTZn4tylTBgjTuErGCRhzCcr+7EAjHdHKbKlUb0///Mn5tET1SsliK9tdL5+TRaZ++3/9Dh3MjYQDeDwdjDL47qzoQgk4k' +
  'ZgkAmDKrfv4/a7VIG6LKXMyK6RkgA584hKQQeMGGuhfWxWcS2YwZ32N+3//o9c3nnbR6y1pU+dv/6fex3lIJO/kViMao8HZetoM2' +
  'VUqHlmQxEtSIyiAnDMs1YWMnLVWXjxkTG0XTHoI+//s4xGOACsVbdeYkR8FMJu68wYoQxw5LC+pJNrVTfmGgaNar5bmRzZysZwsW' +
  '7///99//pRTvXd0Omrt1Zfvr6HIX1b//5eVkYTmI4X/by7OZiAgG0irhMoqWJJnEIKif3JGYbz4rm1dhX+Gm4a52pvudV7m3Yxfb' +
  'g2vtvdobX5pxX/3JGnlNYQeCuRAAVGpG6IgHXlUjESX+I8CHgADRkibeldtckcbialesSaakYAhlcLQKknxiBzl7H+h4biGJGI0P' +
  'nDCynFNKhyaiPT8iTsCvLGFRO1QY//s4xHAACrVvc+YYrslREO2+kmAAjCSVtWlYsw3OFqjGLQ2RpGB8dAmL+aa1dE7OGSuvm8aD' +
  'Hj/+WAuV0t4iYr8ffvjeo+dUj78lMYb2eFd/eyVj7z/aHmu/mtfPTU8X/63r/H3aSJT7j////1eaBYG08TigdAj+hLBoHQEjtcbb' +
  'aTkjTIJJaQAcNk7qr+LAJQRNYGX/YMxWgJjApCsKsFPDBvFjQpaWo64KoD2oWLEkJBGeSs4GaZgh6eWZNIdd+rkgjX92FzcnTBPB' +
  'yb7Q3MLPZqY9QMWz//s4xHyAE5lJdbj3gBJ+Le73MPAC//av///iLpYnvlRt9t/c981i6/xHeZr/X/WaVOdzcnGNS9NfbDnUH43/' +
  '/v///+//niSSwH2ct+XJ9/////8x4tZ35CoxNc5xswMw2yU8UE3RMHAJ9C2cXI/74NifWV1nuep56zrdz9nsi1yTRQoknCwWbjY6' +
  'joh0Z0LP5ni2+U7EznGoH1nMOf6rAVmNWe9+8rr6vaDuvpvKSOFk0oVCTFDn5yta3LCfsc14uKum7cdh75vndImr9zhM1z9hW/rB' +
  'gql///s4xD+AE8GPVBmngApfMi23HrABB+///jO42L//////7gxc61//////bVNX//////pN5QA65XfdFINnWkAiPCAADtQhqePc' +
  'dxbWUbaEnFGV8RIrTUcaLx2AQHhFkgQH8jyA/HbIIRiaKwXj+PBkiWjQttN1jufVyfSBubnGHjvZ6Yn+bq83fTCYmxdsz9RD5h+b' +
  'n74YO8ln3Kq1VJlx4qk963//lnW5lPt/5iSDeUh7J5x1Wz/+IVZz//8MYb3BoaMZX/8XDXGVHxSGAMse0Su7auDWGrCp//s4xAYA' +
  'DHFxc7zygAl/Ei32mGAGX1QY6cWWGNGtiS7NRpQPlFkcxjMqiICiruiso0hUPajqUu9SqVCog9pVmSyXf/0yOR5aptVClM6ovVnL' +
  '0emtHoZysZZjFZWcplYpl///96GFnpduEFDQoAFRxxJuEAkDWHqVVhdH2j60SEzll7pYcSUY5RCzl9sqKJWhC0qw0+HY+CW5lcxD' +
  '3bz/0wQiFkCJsqBo98RES4lcxCCVi0PF3mnCCs688CivJhF/9ZcaPCguaBwaNuDKqiTI5HI5HHJII41G//s4xAWADAFvhbiSgBGB' +
  'm61nMlAAhGAELRxIYFLFIeaqXEb4xQ4qEGHXOCKAbmGES8QHWCQeFu+fecshUN/imxyHu7kZfbR8hBgoyNUY3M3nb/fiqKU5w+L/' +
  'WVKub///yv7CYdHmPkhWJgLl///v7xkrABWBCY0lAYXWkMDyGljLLKseortqA77C4OGuQOxeQDKcwsAxlOQBjEECljaxd2MjX0LM' +
  'oyxvOyNq38hUKVUVUQflnfi7FrSMtQRTZKookZTxCTEN1ERg1bVANpyORNtuSQBIomNg//s4xAaADJFxg7jygBGEIivDNHAAAeEZ' +
  '8oLsKaseLBFpErRWm63sggcc1RMRESqVBcIDpnDjnMmS6MUqodvsf2///zvw4HBRZnM07F+huRTgQkCClshylqw0ojt9W28nbhwU' +
  '19qvWhWGNZ1hM1wc0hc4JQyw00B8wQe1D0ZjUC9h+XUUshqlBhgknrKDo2KHlXPGBoNhraqHoYer+joiXWf////1GjDUiXEY8dyL' +
  'o6qXNuc7sjqhM1iRAsKhGJN0u44NrMClBxvqAwNK/sVIyq2bTZ3TbbAN//s4xAUADATTjbj1ABGFlu43MFAAVoRgB3FYMQVY41IZ' +
  'p16Q1JmNGRhoCwjkKFxCEQDBqDE5mUYgtg1i2KqiycY+yo7OYpMwwKntf+nov//+eeYp5IchQSjGEzIU5QMLNRO9kJf/8TnPwVcA' +
  'CVRNMSsnnQMAQSgwA09S0YOs1r7WVQU7Nay3K0Ou9q9IISIC7C4IB4wBVihjxMDiCu40cjC5xRjK1WfnGWZ///HlOyEQsRHsDaTE' +
  'alwSTmHjIMgJ+o75fD4IeVZ//SQclWBsJ1fdNdeOB4VC//s4xAWADE1Nf7jzgAFkIy73mFAGs2ACapk5yVIYqhm94xrHf3JXHl2c' +
  'Oo5YwXFQTNaxUwRCJCESqqGtV7V/dnq3//v/RDjEkQejZvm/+bxhi46XGhEbCsazi87ovr/1f6RHE5w0GxYA+Ff9gACccSLcABQT' +
  'A3LLUaok8YxnzzJfBxNGujoq2Z5SsZjnHnTIJnVDXfRFuRpTPDgOcLDwILuQiopi//+uzJ90SQk72b3Ldt0ZXSiRcpw7//QE1nCC' +
  'wecFlGFqBgVAUVwqoDIBo1CS4zUH4NPU//s4xAkACoEJZMwgR8Fdru32nlAB4GrBEOl5q4omWjdSmNNkQudiRYaIsRfOdESvdS//' +
  '//V7LNQsqIrGM4Y6iSGM5Xvsm7TFGNgsDoiRFV/5HiwenXVqAApUaJd5AeDwhKFCBlOdBiVgLWoF6Qd54uVVQys2iqzrH9JZN25N' +
  'aJuiK5XIqKUwqcQf//zvo99XaZka3/z62fRP3+RTkYi//dGXzvrOgRBgQPvHDC2yNQAALJdJa47dbU4nG4ACNIWYekRtAdA5RvJS' +
  'IGYZepIRoBIHkgEx3E1A//s4xBSAD+VLd7j1gBGMIO63HoAAtXCovJcD4OwvPPVpsHWqQTkzSzU4dPHmGKQ6DPUHknNXVr4OHkOr' +
  '3vOIG3Lf2MbTfa3SR4//o2bCMXMqXMXu5/5p9T9/1qTMXPw9t/udfo0RnfLfxXUAEBXLbYpHbbAwIRWAA1qBdCyEDI5Y6VyR2Ve/' +
  'VrthaaQsPSxWIHiLQxilFAXnMEw8VIIH6/pr42xkue7s49P/9v4lf////uiDP/nZr/+dpoXF34QXe+KyTqRDt/wwXP/ESwkqB/2/' +
  'tIHDlDFO//s4xASAC+UzaLmCgAGEmTH3GJAC0WS5gptLnBel+A5DHZmB5bDeLHArh0HUYBkAQRdGEGHDgOgHcPhhVRk0O/sRVe3/' +
  '+/9tupyOQOMLstxAXDxhadmsUtGX/OcPjjQ+efojES7B293///WkUltv9ddvv//dbdgAAPVS6uQozaXsckayEYomlNkQZXogpI1S' +
  'yeSUKj7oFSZFr2yqu3cry4x/TZ2bfnJJqXntPh8k3uJdiUd/vxT+Q/vq948xyjjgoEjxo69RCnVPlqvmqgAAoTJHImpJACAQ//s4' +
  'xAWADEEPd7jygAGHLe0XMFAAIgAG9pLoM0jRYGWrTg4772203EHw+Iip2cYriJTjhQHEBQSE3DpR6o8iMyO9GTqTqe7f/+dj8PgR' +
  'RelUcHGG/ma5Q+74ue+wiHUKIncwk91F8PpIfFAaEP0et4U5DKuWATjNRxbbxRWLESXTS6zMUkxDgcFCnFnFiFMJB9AgKucSmBBs' +
  'aBRFf36Xr+/ob7f5w++pSmVwkPW/tVkdctTMSQkhOIhos1i1XUwdKlpP+nf/+4oKuOf8ID4APiuSgwOJSjSy//s4xAUADB01ZrmD' +
  'gAGFHq83HlAAA5eWJi0rzSpWvynvzslfmOzouMEoam2CI548iEhWMmHMLlYoODQhryP0eYYYev6N+e83PoY+Y9edR2up40a44a1V' +
  'dq2Vvm2pX6GGKNybK543AmW///daAADJv9dHd/6OAU3RgBQYD4+ihJqge0bVG4Dg1Sts4dGgoSDgwPB4GjQ+o0YJFq4cOosIiDiI' +
  'wSKoiImNx5Cudv5f85VOZznXmUqGf6G/9lo8o49xch6SrlM+JBZ5b/+GC9UAAQFkBSABUUiW//s4xAUACul1a72BAAFZEmzo8w2g' +
  'jUF0I9CIbWJBPWsKtb5RT/dGIovZiUUIrVYJ4Z0R2tVKI+llKbUqlYxS83/oYrf/rLKpW9P+rebQz9evM/0f9HVkf3ylYpSGAnAW' +
  'WUSEDDpvdlPBECzDrLGkQ7gVMRP7iuXuqgrIY4sm8Okv7JEDQq1rTMm9CyKuaAL/2k4GLcv+BAAQ//Wwn5cuBAiOc6ISxxTi1bBP' +
  'yYICdP/lHaRd4YB8gTVEpmU5GkGGfBDCEBQJwnXafizCNwLg0hhaCXxslaan//s4xA+ACqkBbUwYS9FNEi5qnoAG/9ZkLiEsd26E' +
  '02qeK393MBSQTbi9VMCIFR///hC1Ut9qsGFVASmTM9Pcpokka8X///wwsH3myC7vSVJBIRBGifHchqdVd9vW+sz2ejnG4khMqZlj' +
  'QFDxGzqSjYriZL0//6j1adD7lyTSCiYPv/g0FL71vcSGqafWRFToscMLcn//rcdBw2dFB1SlMurAykdKAQCLMRcQNAqNm9pQqvJq' +
  'aX37dIUYIgOYWcYKnOBBMFD9jlD4CgxDBQwj9k6eXqZ2+v+R//s4xByADCE3XBmigAFaLqxfsCADP/0/dmAcH/QSDwsip/5XZhMe' +
  '4cFAO6q8h3HjQUPCIdb/6QH6aD0aIgaJN0lMLSOKSGoQyG2mO9PU1FKKDOrQ2ceqdQpVmeZgoIgsKQUjEWeGRkJqhJ3Qk7/3MZfu' +
  'fd6enf/9GQz+ZFbut3R6P/p6PR///+pzvKjsUSWOmO9eRQBWuTuqTYRAMBCmRVI5QeFWmCosXm33IH5MfJmNhuqg6rjc34rzHOlM' +
  'ef2HoWD0CoC9kILoM5TNGMDRCv/6kDdIuImj//s4xCIASpi9b0ehq9FLqrC0xAjv/blg7rrTTd///iI8Vh178Gkgq5vo5bBOD943' +
  'zluhf2mCBKsjJY115jJ19qCXI36/ss6sR7vRXVVf/WriCAzMef9vRnSjf0zsp5XIs6EnCFOiZyA3o5J0/tOYQHthhBXOA7/8siCp' +
  'HL45YkUwXh3EFm5uLMeirNvxd/Vshl0HBJPEIcWikx47kRJhnNBWbMHEB56mZUwZ/5XraeATS4udrE8IBELqFECWLv7/8rUDTwoI' +
  'BGp8hCAAqyBNQgsMAEPQIDL0//s4xC+ACjxre6YMUnFMkuvpl6BaktA5J9rXDEdLNZSBd3UkspHHLOpT/3do14uc4pt3bCVrSVd2' +
  '6mXeE7csix7Ly96L74l/qBXQde+sGga///aeOlDB8++YFwgAuAAwEhwvSBiFfprGES6UpFFFIEsUFIfTCiUPDI64SQQx20wwg1Cx' +
  '3X8nScWIIdklASoA3//B8H3n7GiqR6hRZuAATPif4fLn/6OgHweeLlCEeCgJyApBHYC8AKwgjSCMSYSPLgmltpro9XVQWVlpEx2R' +
  'mjCjz/WXF3n4//s4xD6ACnSJWOyYR8FHiuudgwygCJBT+fiAmLVnY1QNCIjiJpUQgqAwoKiIKiK2g6Ihh79olUexKsJuSRoEFxx1' +
  'JyIkoQiSI4v66SjntaZozIwwECMir4HxW6dLVjoDsgQQ7/kK5mXNVJlZFZFdr//1rr/tUhzz/pRUNmFAsadvYkosVLAsR+veQacB' +
  'V4JpDAqxYqBV/ybcIKEMIMzGuFRCDark0NKY0f39yrqo0mSrnyGEcqIYjBFPSXJndnuw6dFoIXhZAF1nSv+SU9AxgTaLsuQuj67P' +
  '//s4xE0ACsz/daeMS3ExEW2o9Ix22W5VzxKRMjNVAGjv2allScBgl2H2Y7exNcSbeJId5Yj29L5pEzZrQlIQJsCGUs+mCaWMhq1c' +
  'UP//+b8cF1myN/VDyKIWQGLMAK2x0Y6WVyMf//6nRyN7VOEETyYeIANrltblrIJDAIkwbmSoNi+RxI5or2OzBQ9EgZESFjkI7GlX' +
  'yV4lDSogYSvZ/zMKMm37PlaKSYAA46z/Bp+uLHki7p3HEKRLiIKA1oAx7+kS4anQVEVTlAFkkBU4AQHSBLkkC0Rb//s4xF0ACplx' +
  'a6eEUelckG40xhg2R3pi/Wx/JA8cPNxoMUYI60NSys0sXI/XohTMkvUaEaCF6QQLMBRAH/KILPBoGnwVO/s6kgOHq1CzXf//14cB' +
  '8eIhY0sAKJJIlJYpwQOasAsihC3KV0kOR+5pgHiBGNvMnEah9h1P3ps/+nCahfd//pc2oM6nQlndG//53//oZ1LT/DGmK1Zt0elJ' +
  'f////829qqMKAjgyo4oUvyoAGRuNV3LBunEC0wn1MubszGYTgFMHUyW2ebjQ3wsttxGa3yz1BE71//s4xGiACkChW0wUy9FZLyt1' +
  'kwk7//oS1PYqRSrIY+n//E4b/+YOtUxGd3ONnnnlx4XsPOCBT1vhz/+urBpoDcZMAFvYklSWA3VeQR0NmGkG/yfE5Sz9JUqZ1Zun' +
  'tHqKiYsLCbI8HO4SHCYldmlGKf/7nOY9BdpcrN//5BosggHBRpydXs5EppOpLlDgqZQNsvU1Y11//7YwVgA5JG6pInLJ7m20AAAC' +
  'Hs9ATUGKowHGEiDKDYCZoEXcOTv838HN+68uQIQgxLDsEkPCYD0CwHMOESkT4C7H//s4xHWACqT9X4eY6fFen2mqslAEqTR4mZLm' +
  'pssOeeLpdDnkvNykSSaKROJ5smdKBOJEphwH07splOmnbC6DlGIfLyzp+bzyKzpsmYWR6Mqpnzp8lyYOQRgeiky+gkgz/rM1myKm' +
  '/dA8cLh7v//////9y+XzdqAAHAUJFVxFIRrPrk2k0QADBBsLBAiUTAgEw2EQEAYEgdoO5HqNvQ8FeXr/kMiMcp2nbZJEm1ZJvtDy' +
  'LMUhHGAjC2yacy3H+wtb2kZvaN9c9urTW48NiVBSss3+WGMjYM3///s4xICAE/mNS7mWgAJ9qam/NvAA75w7r/+v9fHbG+Arv/+2' +
  '0TsN////nGZG6Rtwr1nE2tV14ULER/BmhWt/8SVki6ietv//nwc7Ui4VUb4sHApVAF22klt2///tkiSAAAM+7zKCs0lsB1yacEmg' +
  'Fyw7vm8gLLSh7bC1wx0ACAZT7Y78jgtKk4W0EZE6DmSQjwXIN9Hh1gmhNxeqEIaCGBVlgBSGEJoyKF0bMY3C+OqzOy/nkZk99pOA' +
  'ZBNV5K//slpJv/086k1////4DiqJ4//+MsTA2X////s4xEIAE9EtQ7m3gApspyq3MvACw3yvMQ6We+l8a1T/y5g0zf71rf+YUfU8' +
  'uzVwBLbbbLZZbdbZI3AAAEKy/AGJigKGh0tZgD7JUHQobsTgFt6aJItLsAMmcCmLirVAYrGQZXuYvzfBaHeTRLXQpTxnYm6AAWx/' +
  'Jjf6deLTPHZEUvkoYnpfV45Dwm///Llr3xr4VEGZ4tzQYX//h4meMGs336Ui33DUtox6E9CvU8ZjmxbFN/43/6Wz6Z3XH/7azTRX' +
  '9mdsxg3yxzIAK+Wtp2pJINaGkycW//s4xAaADJkzXbzygDFtmGdplIl4FUPHhe1yZxSOTEkmaKiwkVBWrFTKHZRkp2PccwtX5iUQ' +
  'ji5kMZVf/Qjf+rPDypY2hnQPCxBMplZjWu1SkWyuLCSOPU+pSlK39lEh7/1gKpJUTBUBPETYaAELAG5AMBfhwrmdkCsUWzJAQuaX' +
  'UmaKLNKmgZeoxEoQnaotNNMDjqJOSqn3NjHXuQY27yESc2tITJQtKbxKtf4YUpf/0hXPQXtvGB57mCFh6gGRa95f//7CaAJVAerl' +
  'uZpRg2HACcFLLmrE//s4xAeADJltS0eYq9l7ISXNsw3wKZn7+TGHue0TWB4BhpU/lJtYIkTxllkC9cQNzstj4u5mZNI5QFazRS58' +
  '//1Sx5aGbbnZ2ZhNyHuyGI87INKaSU5Tipm/////9CBxw4JjGBRdG4DMt/QFQAABUkPdDzaA40cOEYAy9psHReXWa0upcH2tWjUU' +
  'USKKRzMvSbGCgEH3dN9Fua3mY7+ktP29Z2Tj6ooXK3Jvm/////qqql92bUmaARqGFKuRcbWGz8IMeLA0///5VSCMGQTPIU7AxMrJ' +
  'FVzB//s4xAcDC0EHHC2kZ8FMoaCNoYmwxoSGmvKCksPbFmJFtil0yVlErnizIsKiIEje+D2WwaAMaygM2MSYCtVbcq01b////9V1' +
  'X8v9j/5V/UjikuoUSpbLQF3//+siZWxbqASCXEBEXOFLMwMNGIhl/rrgxSYo6WUy3TMGJm4a60tZSa1WbWXn//FjKjfXUpjFZP//' +
  'zMZ///+ZWKxlIrG7zKMZ9YySUPGPytp7SJREEjQlI4TGKkxBTUUzLjEwMKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xBGD' +
  'wAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xHMDwAABpAAAACAA' +
  'ADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1F' +
  'My4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4' +
  'xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAA' +
  'ACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAE' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpM' +
  'QU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  '//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAAB' +
  'pAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSA' +
  'AAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4x' +
  'MDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4D' +
  'wAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAA' +
  'ADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1F' +
  'My4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4' +
  'xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAA' +
  'ACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAE' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpM' +
  'QU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  '//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAAB' +
  'pAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSA' +
  'AAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4x' +
  'MDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4D' +
  'wAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAA' +
  'ADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1F' +
  'My4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpMQU1FMy4xMDCqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqq//s4xJ4DwAABpAAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq' +
  'qqqqqqqq';

/** <audio src> にそのまま入れられる形 */
function engineSoundDataUri_() {
  return 'data:' + ENGINE_SOUND_MIME + ';base64,' + ENGINE_SOUND_BASE64;
}

/**
 * アイドリング音（アプリを開いている間ずっと流すループ）
 *
 * 同じ動画のアイドリング部分を切り出し、末尾と先頭を等パワーで
 * 混ぜてから切り詰めてある。そのため IDLE_SOUND_LOOP_SECONDS の
 * 長さで繰り返すと継ぎ目が分からない。
 *
 * mp3 は符号化の都合で前後に無音が入るため、単純な <audio loop> だと
 * 1回転ごとに途切れる。画面側では Web Audio API で読み込み、
 * 無音を除いた区間だけを繰り返している。
 */
var IDLE_SOUND_LOOP_SECONDS = 1.65;
var IDLE_SOUND_BASE64 =
  'SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjYwLjE2LjEwMAAAAAAAAAAAAAAA//s4wAAAAAAAAAAAAAAAAAAAAAAASW5mbwAAAA8A' +
  'AAAvAAAogAAKChAQFRUaGiAgJSUqKjAwMDU1OjpAQEVFSkpQUFVVWlpaYGBlZWpqcHB1dXp6gICFhYWKipCQlZWamqCgpaWqqrCw' +
  'sLW1urrAwMXFysrQ0NXV2tra4ODl5erq8PD19fr6//8AAAAATGF2YzYwLjMxAAAAAAAAAAAAAAAAJAMAAAAAAAAAKIBPJHUeAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//s4xAAACAgtSlSRgAHbpSjXNrAAAFbANhttQUCgUCgkJ0aNG3Oa' +
  'NsAABCAgCAJg+D4Pg+7UCYPh+HwQDFQDB/8EAGD/d0/4DP//u6W//wQBCAwfB8EET+eA1sLFo8TQTFR81cKMxIEeLSwsoZfTOzDt' +
  'r++bDuJMkA83KhpG0PAOA+iUfCOalRDGBKRNCQSTYm0idhzr/+f/rzQ9e03OH7/0X2lX9bvZS7n//tuY/+YqLUa64nnqvOttldta' +
  '2vuISaLpJVRcOkjIG9sJqgBIJFImlIZJE4AC//s4xAWADDU3X7mCgAGED2v3sGAEBAAIBZesV50Tgg8sysXYvnh9Xt/Ag1iOIlDk' +
  'QDgfElMSgsLgcPi6FGj3+b6E3K5pfJk21KpWK32Sn6E/URDw01v/8jE55J2GGL+odT/zhRwP+twhKhxYA1eujM0ZUgbmqM0LafOp' +
  'rBYFNOWexmE01iphocfo1a72q6L5GY9V/0wCZWTn7Fb2JOa1LDQ0kWIhIMNfXViILCUSsAIKgqjg1Drcys6dviWWCxJ/1BdKRIeg' +
  '0eBrESgafQE9rrY5bG5AhmBi//s4xAWADBlrc6YMUzGBMatpgrK6P6w9FsQ/oNzLl0S5t+2seIJSX7dBwYllpCEv5mBIdQy/U75X' +
  'hEqigJSOnGz/9lpSxmf0Y1TXZne2nIpaKlXf2RTv7pORUZl//OwghwhFWRkFgNY+9qwJqEJSBTobuioZljTngXHE7OeG57DCRWt5' +
  '//61bx1vfZu5rhkypucy/mZ2dv1O+g5Hf////t6kf+bV66/t6/db7Ozq7O3/3ZGqICYcccJCQWAwD4iE9Efnji45KxfSXd8BOWWS' +
  'OWVpwL4aocL9//s4xAaAC4yha6ekZ7F/oS22noAGhPFAwDcSJvShOC0LVbUUZ753aGZ3o0TBZGYsGDFon8OxwiTPqtbHpsCv3olg' +
  'oHZVQldO6FgFcoGDoiNLlDav0tsWx3yRBADAQaYNaBGCkwAtbfI3JA2oEy8KRmTrmQk8GZspTHTbSrb3F1UDWi7saqjEJ+4/dVxu' +
  'v1toip/q6dDfuvr/////////tDH2Dx3GG3ZamiGQKiwaAIC+hHDwXSRprKkv/8yZLgw4wLmsgxVAW2Wyyy2W2y2SWQCAAZa50CX3' +
  '//s4xAmADUknbbmGgBGFnm83HrACCsMToG8cVdMUlnaemp5AsjGRfQL4WojCYD2MZIB0QKBmXCGpAwTTJUdhugYKYydalorZbobK' +
  'ofWkYt9kz7f9rt+yH9SCFlJonmbp9q7f5mbmjch///nKUR7tv/Y5bPt9pLJZAABT2NFocyvweRwI1xEkZVYpdaM5AnDIMzRdPc7i' +
  '6+mnmkATkmPmrbdwu18WhV3pNphrdNj3Pj/9jar//+E5Y//6/bX18fJqbKzqFQN+nT1EjoJHf1I9pk5Yk40AatA4//s4xAUADByR' +
  'RhmlgAGDsipDMnABoW+DibcA4lEUKHLr0U5FnQtEkqHcLzQWtealRIeZh5CSkotNnIrGaDGnEIbFo3Xqu2H72bpq/JLcqGeoUCrD' +
  'mH7qmigcFllHheJyiw4wLFRVsOqPf/tUbKzRQ6RBGBozUgatdl/yGrzDCxUwQ4XnjJI1SZphjjpOfYwSxsQKuKSKX767XNb/p///' +
  '/0YmpgO0Oyh48xxpEUv7fzmqSqeTNPPU7cxVIljnX///40ITDDHb/YoJR8tOSgMKGPm4WRwEHGOx//s4xAWADCj3Shm0AAF8sinD' +
  'NKABwCf5iVp5wEl1BEqw5ORmQBoUFQ8oo0RBAFYF5hCwyODmyrEciYWyv0Fm492tJ6ekqEt4b/2iZ//iCxWCV9YvOvWP+dojJFqK' +
  'LJMk6ntqTEJ80/5mZ/sNRDMSNNjiVeZg8ZQjLrqzLL86jf28O6PGyD2RMVC/JjmH8aj08iPFUjIzBbAsGhVnqWcm+7+1Pvneehh7' +
  'N+96un3a91ZGMcqTr81Ps/frz1cnMY+z//////+rmGR4ZhUgMiytuNtyWwRJJJMA//s4xAaADJTzb7j0ABGGLu63nnAGAM9EqcyC' +
  'wm6D/iKqkf1dtyobCfHmixph9hyCpyRWaF2kV5GjMocWTfsZCbKjG1SDbh6tiWGf//MVT8/+73qnFMtfV/f/xMcEUm88Hxuy4Nfa' +
  'QBUa31lhMQr9dbJbWgUFMLWqWhWmUIcqiuPdEsNbrLPbalXYu4nMQ64vDBolIWY45VHCQ3HT2rVpWezn2NHruaUOOYwdc9b//1q0' +
  '5UR/1Uxz2RlRnb6Mc5v/////+ltUc3Sh5phI0ZQqAE/msclsaUCc//s4xASACvTrb7TBADGpJC23HoAC2KBQhUjJwfwFNL3lrSxm' +
  '4CcigQeujlUwpywoAw7BBiDWeXMzqprwZhLkOoZzFdf//+nc7mMZJWq5jMMFQyJNc8kQVtuZ/+mqWEQuFHC82AbLbZLI3HbLa5HG' +
  'BAAQVGKrQSQ4RQrAoMqlUGerT+uxqNjTjw4AFLHklqUSHAr2Nd2JG2IgpA60+Bt/Ni7XVXF//rff+Q0DDOb/j+In+KdPtD7ofczc' +
  'f/z3X/az/vf5iAIA4IO///UUDFMgaKy3XS27Xa1g//s4xAUADDlDe7jDgBkyB+o3sjAASDAABkWPFkeVC0vDc5V0LLy/HYhoLh8b' +
  'khwuBIeuRMVXLiKNTUIlRepQeMdCI4ZMoYYphQshUkfJlCw6KjaqjnaL922vNGv//+SSnTdraUN///9Rqu6ENAAODBABQavDdzzV' +
  'MP1dqa4OWZXGJVSyyNapq83KcYLIxnkn4U8IQeLAsCYqGRHSVJgMhBxQ0ixb///zhgDGR7/lCbkPf//i2aKA0boVAL0TSQ0I4IoD' +
  '8WkEBITAwEABCTOoXSSq42WURvv4//s4xA8ACe2JY4WI1flaLez1gwk2Sln3QhWm7p53l9GOntl/////+v8lJGr+2e/Qiduc5///' +
  '56nFwAiJAAQPOBCHu7ssseS1/JK25ASUFsA+he51jclwaKdTQbMkCICTTytI87ZGOFAHvaKT54naIHtBA8k5XsF1OdznUQGuRP//' +
  '///+v6F7vq+Yxt/WlpPdDf//+pSsWgE8FVyz0gBLJbG3GGnARonROmlFTobuPTGNyNaq9j1sbyyMN0IsRJpT+X3dzI7PtPWVvesa' +
  'pOShrm0f////5OjV//s4xB2ACsFxZ6eYT3lWEGhmtJAA+dhqE1TTK+RGI9153mUzr///qz2ZHjKIXcZlAEIAFAoMPGP7KMOpHlhk' +
  'BZgCqhrzzV65N415ydzxSU2ZOTElo1ETAVKpWw/rKJiel2GfTb/18v+4J5fq2rP//jlkAwcLicOG1kDJ53IOHiM///zYuXoE0GUI' +
  'YEo9qXyWIk3VY97J71JyN/H3nMhipoIlISkvj4cH8T8mHx2kiYkoShuxDhxnCQJd062Up/KNk03QX+umtSOeTQSNEzQz6BcpVtsb' +
  '1akC//s4xCkAEM2ZRhmWgAFIk6y3nnAC+OMcwSAKclFmIW8EL00uZJ2zRm7fhzRMx5oMPcdC+bnRxlP/XX///+pkE3EbHObmBozG' +
  'ZuAXbLGS3UCmFO2gMQXI4B5o+IRlD2ctqhI0XZiUUAFouEwlnHnEDKrT+5cuD0uzGf9H1a7HKcvorDb/oPO/jTtYaX52HfO/1Q6d' +
  'DoldhpIacsFaAHuUptJOBVcauFWjxbi6oXesT9aUXY+/kxS4A5sTrBegdwhUcuytANhBHJ1hAtyMjI4SuLAAIfwx+8Gg//s4xB4A' +
  'CsSHW1WBgBGxse53GIACoHWjiJA/RFJSk263HW7Ef+obHMrEBp5ASJcAJW5bXI5HbLYIq2GgATOT0XFhefi5ooUd+jYCWN3MkyBd' +
  '4EEeNUdjHURBQehUNOjreEbLMwlOdA+qe/93dPn1X4X///9ES7t354/6YSPG9X//u+iVfu94BblqlJGI5Tf//////6e9////XIxa' +
  'IU3ulbdsSTB6lzqsiaoeeMBeZ1Y7+lqMqeOo48Nwy6m1nGuUOv5rMRf+s00o6amEi3/+bjq3O5v/R/O6//s4xB4ACvUhdbzzgDFX' +
  'o230wo7mtjxxtDroe3ct9D3uhw2BUJuBU7/6zEskRFnwkCd9Lq7Ja24CmA1STTIrAOL44a7/H9WbbdmsH/N3KXlpauEMvur18Bw6' +
  'QUOGrIT+TfUcUYv/5fLl//1qrLtXoyo7lAZzOPpziZBx1n/9IFKJKhM4ZDiaAF1k0bctabBwAkpFtm4HW6FRg892Jl2RFCgINAaQ' +
  '7PRio6FnKV1RD0b9FzalOYHRlPrr//QnIV0PuqKi0R9ZWF5lsQGlj00lRy2f+t8OiEow//s4xCiACsDxbbTCgDGerKx3HnAA2qFy' +
  '4qoAWiWOxRNO22OIUgQAAIMLWASNKFAI5lyMXc/qqnu4x3MFgUlnNPHzBIOccdJ4kVcvNd/POJMYPSZ5zmml6oZ0fU80cP7tdm3+' +
  'rIQHJiGNzvnG6Jo78he7cyYYbf////rKioJAIuT89QCSAADgEgIAozEOXsTyaoY8w1iXU1/Hde5YrX+SMACGd1ukEYAIM58EQZTv' +
  'm6tuf4pP6E9DLcyp/Zf//5wEplQ5DI6vQ3//v///9XMYxw40XooKC/Gv//s4xCsACtVlT12hAAlUkqm1oxT40AAYUgACyUoEwTpD' +
  'TbsAFILttNk3hnnkU5U1clhABG6ULp7DgQFsjSjmSTEoRKR7dWSNK/iTI8d0Hf+qt5A0bxqsIjGhrZYGCAoKPd/rKZPeIYWMCy0A' +
  'KMMAAAkAUISjEvzknUDDHDi7rbUr/50hJo4Zj+SzgUiBDwCaYWoUf6nUWDgxmRlP/p9pH+DUPd/+vneloVCJkJLKMHA4/1rEf/zG' +
  'sVQHZEsNaDIOAGXOtpNuJKCCwahdfYnJFeS4GmBALb1z//s4xDaACqSBTa0YaUFasWy1hJTfDo3IVkYZYtEQ6qxawsrIyqRvT38k' +
  'WT/+pWR67d/9lXLp3v4MNYRSNHaMtUmuqSkYv///p/zGaiEKyCzo4eedAU310ttobkC5OTTOlY4zWRDFXKXu71mhpsjP27lnBMsd' +
  '2A0e7tdhIZNvm5v+B7NqLlH//////yT07yMp2U0eTSIgkGBNMlVEiwp/8QlGKPhs6XKMJABSgkywZArkn1lxOe6ZZ0P222UMmDh5' +
  '25FzmZjHHuakZaZaYgsz4dpqJXO0jiT1//s4xEIACpz3b6egrXFQDymplhiQOayiTicDg+Fz/hYM/wi+P/SQoXFDbRTSsqoBo/yg' +
  'AD5RLXSTEAHCARWATAc4ASC8RqzSpYsSBg6RBCL3MdVmGkgydLJkYTQW/jWCmR3+9/baqAwiImv3/+s1kdRQIGhm/VNWMg4mnQxQ' +
  'wcju23/RysYrN/3WaRyg0agAJmNFCsAgwIKHCk1EJQqZarK1+O5T01uNS2TWZYQSwkMzIiHu5nE6YMd3TIR/X0se8p4YLN9Kqrrw' +
  'VYwqd/lCppAYF1FGJfSF//s4xE8ACqFbTEwYR8FSkKtysDAGGAF3+paFKUu9aJ9NAa/pWukSTSLQSIAOemcMxAskjQ8CJTrq1M6X' +
  '6sdkTeQW+SddIXBzmQwI9ymWj+MAZFwuFhdEHG46aGA8TYoomQnJeKA8BLBqE3I4x1BXnh6hyQvg4xvTHIaOkWv8k30zdCYl1lmJ' +
  'oj/rOP5ffTX9bkuMIShLE91qLx4tdE33QQUg6DrXQUPc+mal9B1S+6D/rR6vt9CymW3t1mZLvTN2AGBkLgUMBpWUALAJQAMneOIa' +
  'MNIM4tKE//s4xFuAE+GVVVmWgBKCMao3NNABpuEgAClk2zz6ddoZCMIWnLK8aKYlZsABUSJNPlEegWwojWSJqOALyFrLo9S6XjJj' +
  'EnqMiRC0jlOlB0TJElXdMyU71sup7IafqWZt/1sTSVNPMy+71dQ+ubJKPDgEnFiFQHMfWTB2CVmqK3TSRbUXkepTI//1ImhLnCkX' +
  'Cyl/1XqOJo/6zREnYGUAQxtxp21psPwTyieuS7hpa2lE/3WNjfKuqwjZaEUDBCbabEehNxb8Pdbrz75+3FLv69bqdLI/bXrM//s4' +
  'xB0ACsj/a7zxgDFaLGoplAj5zN//Z8HYKGh5OaBQmxJxnTKM/9YKuFEMUwFTxgAAgAJIDIBEabGQADGnhgBMRk0aRzDmKtIHy12N' +
  'e5lkImwU1y1ypBzboRsEHDDiFHZLKMCEEWQRcZGWdX9+rXX//v/9l7N92/6Ol////840V3xiOgP7aRmScOMAMAPNONMKBDBUC1yS' +
  'GvCttuu8YCxM4CY6Hi4B6qGjRx1ZEV2/7oRsEIZRvTvXXVPnGC77A+GAsEE2VM0WCd5+z5MmQbn2CATnA+AB//s4xCgACcyJTi0Y' +
  'R8FEkOt1gw0s9PDTJqQYJcTaNm0829WfFMa0O9AxMgCcqZRLjMkirUSN6eApu8olkKGRHE8/elBnDqDsbN9z3VqCvfnjDCztL3c8' +
  'JXBMw3/+sBMEyyTBENUA4wgWglsCUiYpkbQicEGydOVFF3H/tw1BrAbs9OQ0M8hTXsjDzWtCDnUEp8UcjhWBjVCPBM4S2jJAx3f/' +
  'h4gcA+PULw2JQqB3B44gKO6n//FBKzMF/SAO4hKQSkFQ9SB5Ce0ShgDsrNf3QTdN2LI5ibbn//s4xDmACsyXTU0YSUFKLyrpgwiy' +
  'OoYtHqVnK7alj+jeiFk+j////9boq63qpDu7HVSVQzC2+xfVHZCuoL///5yjksmGEoFalQDWAAcSSJSQScEyc8UGYCINGXegemnJ' +
  'ZIZXpqiASYjU0pYtyNnLkygqmozMCMgleSXsrdUDOIEv//9BJ7ygO3hQ2vATxyyyxQ9h0Sf/uZKkw6VoaoCl5AUqm4CV002QOouD' +
  'FYeM2hhxSs5p5hNHBBLcJfd+yXlRTtUd0Yz9GV5YpDSKrWjzN/+3///XY7my//s4xEaACkiHU60YSxFTruopkxT7VR3mETh05OhJ' +
  'zvf//////TdkaOUgfUIGPP7VBq6UpOFyBQ0S6XobyOw5EY/P0E/G5mGpWWIdwTQ4xJwIRGkNKJ4zKCH45c2JNmq5wwl/bzujq5Gr' +
  '/t//6IxSVHCFdSGCOogoc0cUzggn1f3dYEc4XU9QSCIId4gf6cZAuCERhATywp9JGFmPBtWwuGOPw8oUqo3AminCqIoahVMruqf/' +
  'SVjOvOjNyo7lR2//mVkrrVWYSHiIYOFQEBRiSQdOh0i0BJGH//s4xFQACtURWUwMTVFZnelFoxUwxIr/9Q8AL0ArIXeCw4ZBYUmE' +
  'jXaWDTUuRe/HowTJHGTjZFHoY+a3Y3Qt9jJ/IBhjHSXtajZyncSCFsipb//8v//+ut0uqdlOYz0dH/+j7f//9+uxSswt9qeAIG4L' +
  'lHSIZQotalk5754LOLR9IM+O27vukL/oQiTMBA4RmuQhf//0Q60PIxG///9O8l/radCD0JOUPuICQAFF5z6noQQFBouC740PfyAe' +
  'B8+CBMTqCIfDOJ0AIpRtJtxJwPWLHL+pwhib//s4xF8ACo13UUyYS0llpCpVkxT4plGXWN7ik6vBj7dJXFq3IaUjymwTuIOw0xv+' +
  '5NSmCDoKNQ52ey//9qp1/+/Ltm9kv//+WZ0/+Y1DOhlLZDTKJyo2HVlQApY60nG0UwYYuJCWVcKpD3rW2K5XNUDWqYBRJjoijS+g' +
  'myOH4ayugiL96lUrIaahscwuczNMb9l/2MqSt//p1mujuS5jP+v/RKSL2//9lU/ybCbLnB8AQlwqspuzfyRuWVkAA22UxYoyaYMP' +
  'gIKuCD11JA0MPyuD4qyZnDqx//s4xGmACpFxZawwQ9FaLq02nlAG2Qvg+R63ZwsKtSTLfJfVDKzoYZBLAEKIXEaifgmS3pxQzpxQ' +
  'XH4pjmRmV+Apj3P3U1KEvW596wnnNW///byb//63/e99b3/8d7SsmPEy9V1bytzJhjcPSPuA8j4hVqupLwqa3TG/56RncaWWPGz/' +
  '///mk4ff+pgf2S7XXSX726N1vIAAGjb5lDaLKkBE9+XxUNHoM1l8vg604tMuEmky7q8/BvqR8/RrYWCGpFi5gGQ1x0UrG2zUYxNk' +
  'nGZ7PFZATzgu//s4xHWAE8lJTbmngAKBqi43MPACnpLXBiVlZc19/9ffxmFBrifWs0+Me8jxOOFHxKEZ/4UGDXx43x6/d67w3MsY' +
  '/DIyrFAySKyJrG8YfW9403i6/+96/tr/41e8c60QjDrc9OfxKEjyDQAoingOIjUFyYqc4OAAZliKRlLNzdW/yZn52vp2GKC0jT0n' +
  'aOcYCIZfObrKrM87n/dHXa91tREQlAX/LEVzl94+k9QMApVToT1nSrix7/ywMuddGAZlII90lNpFYKpIHp4E3WZxSc1ufmJ6UJCN' +
  '//s4xDeACuyBTv2jAAFdsGvphCl7orKMVx713xpCL1LDDRrJp/cU8aPY1Vkyjf///9V7/9DDDDGMt//+iGGf/////1PPMMBQFwNB' +
  'gK55x4/IDAAAYggA0AAjAGqyAsQaomOAoXWgU1E1MsUGBmz+DSnN6iW/jaZqzovRWqLL/ohlVjylMpfrvsnzKVFZ1Ym6PmPdGoZz' +
  'Gdl//R8zTQrLKsCQFAX/zxZ+GgBKkYiU2ynAKFG1GGqOrSNQAKdh8kjYahdW72vvXbDkZoMCMA7ODUos5hCouz+d//s4xEGACoEb' +
  'Ts0YR8FXH2p1lgisBZ2TN76k//9+huZ/OVasdF5u0Kg4KqQOnTiwhT/kaiZoStqB1yJqAJTejJSVJSC+jClKHsa1Hvsd3HpRAEXX' +
  'ND9iTVHH0hnFJFQtbsIhZQcg8aP6r9uhw1/+Xl93vqti96BgL/KpO6HRuyoczPqHKpmHPd/+UGtwwbMqAJJAAgFWhKsPfPJw0DAU' +
  'gHCPzQROmQWGDUdKRTWVzSqCiWfUyMdH/W1+///////6KdCgYMUIA0W1KnRai1DN/0WrkRc+p1CM//s4xE4ACoEHXawgTzFtLiop' +
  'kYkpdGdjqhXZGOjkVybPCBzwEafPRaoAAsApWG8DDzMvwaWE2B0AsipOG561Sfd/Gez0BBBdeCAvaLNyfvS7iqy+S/VtKrxQwQVn' +
  'V8KDUBA1+DQlO/EoBO7Kg6GiJvVnbaZb/olYNiUGnhN1BAk+elrdbv/17dloHAAD6gSAx5LOeG6aonKzsHgZWQhWfKp+YlhPDZC4' +
  'Bdj5JGA+DWF2Jh9ZSE/GCPqNmLx5M2TLRgB8NC6UikSw41DwMBzlQWaKB5Y7eiyL//s4xFeACqyRT1WRgAJ+Mm53MNJDuPc3pamE' +
  'uRSHsapmZ/+gg19aJoxqi6kmTWeLiJ90ESTMPtpmYyh6oGjolJXOmZ0tOJoIUkX/////+nUSBoPQwFoJwO82KUBitZ/faU7dtyAC' +
  'UWAB2cODAJYuGbCS8hbBrze0FnOdcOIQqDKY6W1HjfbkNE6FIBSLSyxq1oXCuYSoRber4TWw+ARReHk298hqh9vpQe2N51bOLPq4' +
  '1f5//ZcQon/3/7w47Oj1hV/5znTbm1f9f1+t4YGTFv4+fPT6nlo9//s4xD6AFBVvXbmXgAFPi6ortIAA+szPa6taHNb41nX//16x' +
  '5osZYiMKP3//8/2/1qFGAqfQCzzIBvABREF4CNQbGSbwOZEEY0sIAL3y3VepbtXJDKbPHiylRSUCA3gwy7fex9oZREhqX1FIoITO' +
  'S/4dBUllRQ8Cp0FQ0IXQaHlda7f/EX9uJUyQGNllAK1ljbkkacEYX6zNAQxz0u2OkbWWRXT7U7oYnOHmGoJPGmdR5xABQ6omD+Ke' +
  'rksdRARRRr////qxn6OW5YtiowEjQNAAG3euKsaa//s4xCWACvDba7TygDJ+sup3MtAANf/kQ2FmiQebDDQqoANyOtxJIm22yISI' +
  'OAAWtaKh1jxn3KapmYrdkoGUaw6ctvSqRy0ki+WGIWs8PAkyQJA2KQ5iRHAS5sgXi0vIKJwwgXcyKlGs3LhLmE2SQCXNTpkbFZML' +
  'z/J59/kkf/9SLmJUZ+gplpIbrJRM3RJxGsZrepFqtjdBRtqmmgFUKI5ygXGHYURhxLy8eb//+2ySm/2WXyAMGJ+Xhhx2lNx6GioA' +
  'hsAXCAoFOyRyYaEPBk7xJYtSStN3//s4xAsACtjrU12igAFZsKrplAk/9WU4cluWxEJOHmqNIxqCo9iOJHnKUVdjOf/5lRzGI2v/' +
  '//7lzUoZymEmYz6B4ygoDR6ySBqWho9tV/1A0p8RP6gC3lBRpBQQIiwYEsL0MLfaV2ItOqIMnB4I/6GYTtA8ZCYuinVCSiHCOOOh' +
  'Jbf+EA3qckYzaO3//927fks3FbeLRuOdlF3VLXk1Oy7m////zZNCdflCAFUADQxghNglwKamo2amAY6qu6j33waIc9sFX+VaEaad' +
  '2qwHRVEgwwEDZDsh//s4xBWACsUVUayYRyFEo2x1gwk2SfmCPhBzULo4F////+i/9/QwgJlVAUrdASggcBkREiTf/xCAhZZ1pmVY' +
  '5YCmbsbTkqTYegQNZhSrlgJobcYRg5N4IAyXZUEYnuQYRCDoA2tXi3TJuZ2MkcZDcKJSLHEat///z/6f/JWmp7giIwl0Vyu/BJ0f' +
  '/qFCEm1jxRUAEkQgFJRKAIpGruuMeaVvbi0LVi3nVwu2c84ulIgQzxULi5hiDGadBQPi8Rej7a3dnRkFZXLQcj///7C//VN11IW7' +
  '36rR//s4xCMACvVtU7WSgBKDMWx3MNADP6PRUa9nQVf///8eKiwmHFiIBjkutsstn++tqtQDADFGTe2wQ9Ppg1HBt5zH1iMsdKBk' +
  'uCgiYNo3BKmKgdIKs8AEETceIJ+bjzE8GHIReHqPp4gE8bB4DISrFiYCZl9nJ6QHkF/THoOwehGj8CeC29JQtw5iKeblY8x6jkJQ' +
  'uFzNup1JWPdSB02pputOS5uowTl/Wgoy5ggXFdSSKOS5voIJppiYDkNC5/////5ca0uNhIogeX+7bS7bfa2ASCgAAmxm//s4xAgA' +
  'DAFJf7jDgBlIiqmrtGAAbpVsGolqtQlxfPUIvr7CkaFUUmOhcELGodUkNC41PlzibuTqpylzblD7TWOSojDc120Mr92/Sx1H///4' +
  '9ZVRiI3jWbRD+83//mq7K46Zw9UAYgAiuDKFkG5emTtj3MxoCFLAurSWpVf7K+0mvx2KfGQN2yYAImH6a6Rqh6wsECzlti41QsIW' +
  'lw+ZvPf/INT9azVy1BVVahEAjz//0v6hGEnVVQDPnW1fi2QyTiFl6TRwC5qg0zXiQ6P2hd/HvNjcHH2y//s4xBAACl19aYeEs7lY' +
  'kel1pIj4FTE5SaYUziWTDJlVdcBQv//////9WzKLotFyrY542qIS+v///9UZLkuIR4wBxAPqJo4yABECQCmwi6BgGfxUeGqqgIiZ' +
  'iAzPqG6mF1lSMm9TbaaPDZnrzlqO0aJjtTjkAQtBR8vhYiz1dWn5hxIEv/+5skCYSEYyorfhdDlYH/+hK7hwcg0WB28ACItopN9p' +
  'wJGKwBH2Zsbikg5LqHOxurKsuSlexZuhQ3BlIFn1qz04NvFw28DdZfhMLg+cCINgjBAE//s4xB0ACpRNWbWEgBJyMqknNLABy4Ph' +
  '+CByzQVbtIJNMQjfsCruK/9j2mmUBZlYHoQOA7f4EgABleClRCvCBhi2Y4FSNddOtRpLiUt3vRLjE6IPxcsbogIBmPI9D6BIoTxA' +
  'AP4OE2FoyWNo9gBgTm5Pd0fHUw/TpNyCKjc3PmyRgpXVcHh8OdkuYHkhUGE8x//+I//fUNPnPk3PkwbB8a6mt7+X/1bYdXxfgTjr' +
  'J5MafHQTKNAQA0L///////////+K5s0WNwDCYw3HqgBLLtbXJJddZW42//s4xAWADDFLebj0ABFcCulrtpAAGwAGChzo0/YDXkUb' +
  '5qvEunoOp2KcskHIoxhcS3RSEoLL1zVLZoqzrMxTZK91XERUT+7f8aVxVfwtJLV/M8f///PV80vNULDW//mG7//////0QaOFf1Gg' +
  'AgAAKhLgdY00nMrhyhPAQsLBSOrFbP37Veehyk7/eoKADmCmo4jC4ADFxuWWiOtWsJnqgOMTSHRILMPHGWf6iQdtISouYUxRybEH' +
  '6mJuT/O1i72Rqya6AbtZJOkFCwwYEnbo/q/A6rw6ObIj//s4xAqACshdX0wZJHFanulpowj4Dj/55rNw35GLDDtTfk3JzyNLNDyO' +
  'VcKvKrKgMcB6XFgaBp/yoGNbrxTaZYKECbAbCJ+DggAjv/xodsENIuDgDQbAEJBJGpegQKDVVTx0QdRFA6STYuDEOEuRPE67yYRR' +
  'vV1lgcVhIJOSnbgGQWMh7L+GoGN/mq/q////ayOaXrL5uKcHAkzYQC0QuDn/4iCgqFn1hMLjFTsAAoREAsslQBUY/1j3TRgZnDrp' +
  'WDzWrHEB+EZCQLRSlQSQ75FjIbluGnR9//s4xBWACsVvT6ygR6lYmynqtIAESfBIxxOvlPkJ7///9tt0N7ztu4hznRk1ozz1ajPM' +
  'yD////7bVQQJ6K0fbQBRKAtVFsBcaauMLN2Kuxa3FZXG8rlPhjMf/DakkQJRUKCx8VMr7fDjjm25r/4/umzbrauRg10/r//+N3gx' +
  '37Yc/HA2wWGBRxQIDCDl+7Tu//IhNgKllQB5NpHGlWvXpIAwEQADSJigAEBzaCjLjjoKUwJSLAXNZ2qu77zOresN6SmkKIIPQ76H' +
  'aA8XTEqRGNQ0NwQwT21r//s4xCCAEwlpU7mlgAGFJC83HoACmjM+OC5rqoSG70GHDp55ximwxNpu4Y4sMviW3Dmug9d6EDsHxKkP' +
  '4o1O9FPsnc2rx1n3r/syYaHHpONq/e1I8rH1/87f9pLL3m9sYy//dqmofkTh82c6ARdtttdrtttttttgAAD9WDjVizMEXULo0AOa' +
  'l2lYDpqyxwlFaEI4egeQJBjAskaKkj6ig5gkwtIesRBLFfR7kxT+7/7jCGr+I2/5/+If/uOud/pX7i2Tiv+L4WFr//ygvpUoWS22' +
  'yN2O22yy//s4xAUADCGNd7jygBlzqKpDNnAA1oWAAV+ZvSKl2G0UznBWozBtkgWciugYJlYVAsx2bU7g49SKZWIk9B0mQCzsLrm+' +
  'lmdj0xBXfquunpvopWkUPOYzf//2FGf66K4q////yX//qLARgweLM9ZzRww0QSTlNPhzGyad029RYmVJL6av3RUaGC0xB4fCIuaV' +
  'JDg0LnHjRzmY1zkepK5m29dGzjl0s//6VMZ50/8/f/1cuSSyq46N6WNvsk76r/9SoVPgEz4mcS/UPQKNfBAEcyRl2omUJaBk//s4' +
  'xAeADHjTShmlgAERBaFDniAAa7HJmpfnGJY/0uknjeHuTWwSwQ1w4MTUqHcXJNx+tN5OlrZ4ng4yj77h17a1on/Ycp77YzdfP//7' +
  '/qnvtjIPgf4xCK5QgFwI4Lgx9X/DAPmjAHAgYLqDZAyiYrKmNJRRoSeQ5Dmbda1lAQEFagaDsGsSulga4KncsHeCrssHeCu9QdiV' +
  'YK/okv/UeLHolgrUeUeiWCtR4serTEFNRTMuMTAwqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq';

/** <audio src> にそのまま入れられる形（Web Audio が使えない場合の代わり） */
function idleSoundDataUri_() {
  return 'data:' + ENGINE_SOUND_MIME + ';base64,' + IDLE_SOUND_BASE64;
}
